### ISSUE TITLE
Can I add gumjs release?

### ISSUE THREAD

**Issue by ShenKecyes** [Ylarod/Florida#11]
I specifically want an Android gumjs static library to change capi features, if possible, because of the application scenario requirements.

**Comment by Ylarod** [comment]
done in new release

**Comment by ShenKecyes** [comment]
undefined symbol: v8::External::New(v8::Isolate*, void*)
>>> referenced by gumv8module.cpp:152 (../frida/subprojects/frida-gum/bindings/gumjs/gumv8module.cpp:152)
>>>               gumv8module.cpp.o:(_gum_v8_module_init(GumV8Module*, GumV8Core*, v8::Local<v8::ObjectTemplate>)) in archive jni/libraries/frida_static/libs/android.arm64-v8a/libfrida-gumjs.a
>>> referenced by gumv8database.cpp:106 (../frida/subprojects/frida-gum/bindings/gumjs/gumv8database.cpp:106)
>>>               gumv8database.cpp.o:(_gum_v8_database_init(GumV8Database*, GumV8Core*, v8::Local<v8::ObjectTemplate>)) in archive jni/libraries/frida_static/libs/android.arm64-v8a/libfrida-gumjs.a
>>> referenced by gumv8cloak.cpp:57 (../frida/subprojects/frida-gum/bindings/gumjs/gumv8cloak.cpp:57)
>>>               gumv8cloak.cpp.o:(_gum_v8_cloak_init(GumV8Cloak*, GumV8Core*, v8::Local<v8::ObjectTemplate>)) in archive jni/libraries/frida_static/libs/android.arm64-v8a/libfrida-gumjs.a
>>> referenced 26 more times

It seems that the compilation is not completed, and there are missing resources.
