### ISSUE TITLE
使用florida-server-16.2.5时发生"Failed to spawn: undefined symbol: main"

### ISSUE THREAD

**Issue by MoonBirdLin** [Ylarod/Florida#6]
测试环境: ColorOS 13.1, OnePlus 9RT, frida 16.2.5, frida-tools 12.4.2

使用florida-server-16.2.5时发生错误"Failed to spawn: undefined symbol: main"
![image](https://github.com/Ylarod/Florida/assets/67228106/135e815e-af91-4a01-8865-fb52283fe958)

请问这个问题大佬是否能复现? 以及有没有可能的修复方案? 

感谢!

**Comment by RandLily** [comment]
一样的问题，期待大佬解决

**Comment by Dormzz** [comment]
这个问题是patch文件改动改漏了，

把frida_agent_main这个改动取消, 或者使用其他的全局搜索工具把frida_agent_main这个字符串、函数名、导出函数配置统一改成一样的名称,譬如  ffff_agent_main 即可。

**Comment by wustwg** [comment]
请问你解决了吗？
