### ISSUE TITLE
最新版本frida无法附加

### ISSUE THREAD

**Issue by zwr1025** [Ylarod/Florida#7]
显示找不到main符号，换用正常frida没问题

**Comment by MoonBirdLin** [comment]
之前16.2.5遇到过类似的问题, 你可以试试看另一位的解决方案是不是适用
https://github.com/Ylarod/Florida/issues/6#issue-2319377100

**Comment by Thiasap** [comment]
以前的版本在/src/embed-agent.sh执行了anti-anti-frida.py进行修改了，所以没报错，新版frida把embed-agent.sh用python执行了，这一处path被取消了，导致找不到main符号，要么取消所有frida_agent_main修改（会被frida check检测到），要么在embed-agent.py添加执行anti-anti-frida.py
